#
# docker-compose up
# http://localhost:4200/all
#
version: "3.7"

services:
  app:
    image: node:lts-alpine
    # --host 0.0.0.0 to listen to all the interfaces from the container
    command: sh -c "npm install && npx ng serve --host 0.0.0.0 --disableHostCheck"
    ports:
      - 4200:4200
    working_dir: /app
    volumes:
      - ./:/app

  server:
    build: ./server/
    working_dir: /server
    volumes:
      - ./server:/server
    # port 3000 has to match src/proxy.conf.json
    ports:
      - 3131:3000
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      WAIT_HOSTS: mongo:27017

  mongo:
    image: mongo
